export const FETCH_REPORTS_REQUEST = 'FETCH_REPORT_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORT_FAILURE';

export const RECORD_CREATE_REQUEST = 'CREATE_RECORD_REQUEST';
export const RECORD_CREATE_SUCCESS = 'CREATE_RECORD_SUCCESS';
export const RECORD_CREATE_FAILURE = 'CREATE_RECORD_FAILURE';
